languages:
  Python: true

exclude_paths:
- "tests/*"
- "app/migrations/*"

engines:
  radon:
    enabled: true
    checks:
      # Radon cyclomatic complexity checks generating too many false positive results
      Complexity:
        enabled: false
