dist: trusty
sudo: false
language: python
python:
  - 3.5
  - 3.5-dev
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - nightly

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

services:
  - postgresql

before_script:
  - psql -c 'create database zordon_test_db;' -U postgres

env:
  global:
    - ZORDON_DATABASE="postgres://postgres:@127.0.0.1:5432/zordon_test_db"
    - ZORDON_SUPERUSER="ZTestSuperuser"
    - ZORDON_TOKEN="ZTestToken"
    - ZORDON_VERBOSITY="FULL"

script:
  - coverage run --source=app -m unittest

after_success:
  - coveralls
  - codecov
